config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :profiles
  get 'home/index'
  get 'home/browse', to: 'home#browse', as: 'browse'
  get 'messages/index', to: 'messages#index', as: 'messages'
  get 'messages/show/:id', to: 'messages#show', as: 'message'
  post 'messages/new_message', to: 'messages#new_message', as: 'new_message'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:"home#index"
end

app/models/profile.rb
class Profile < ApplicationRecord
  # one to one relationship with user model. create profile form is automatically proceeded to after user registration.
  belongs_to :user
  # has one address which can be deleted with profile.
  has_one :address, dependent: :destroy
  # one to many relation ship with products. a profile can create multiple products. 
  has_many :products, dependent: :destroy
  # declaration for profile to also create address record via nested form. 
  accepts_nested_attributes_for :address
  # yet to be implemented reviews functionality
  has_many :recieved_reviews, class_name: 'Review', foreign_key: 'seller_id'
  has_many :posted_reviews, class_name: 'Review', foreign_key: 'reviewer_id'
  # has one polymorphic relation ship with active record. Query profile_img on profile object to return active record image. 
  has_one_attached :profile_img
  # declaration for acts_as_messageable gem. includes simple validation to ensure body parameter is not null.
  acts_as_messageable :required => :body

  # validates presence of each attribute so they cannot be null
  [:user_name, :first_name, :last_name].each do |v|
    validates v, presence: true
    validates v, length: { in: 2..75}
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    # for use with simpleform nested fields for address in new profile form. 
    @profile.build_address
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)
    # gets current user id for use in profile form hidden field. 
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        # redirects to rootpath after creating a profile and address
        format.html { redirect_to root_path, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # address parameters are passed as address_attributes: [] with all the relevant values inside the array
    def profile_params
      params.require(:profile).permit(:user_name, :first_name, :last_name, :bio, :user_id, :profile_img, address_attributes: [:house_number, :street_name, :suburb, :postcode, :state, :country])
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class="container px-5">
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_name, class: "my-2"%>
    <%= f.input :first_name, class: "my-2"%>
    <%= f.input :last_name, class: "my-2"%>
    <%= f.input :bio, class: "my-2"%>
    <%= f.hidden_field :user, value: current_user.id%>
    <%# nested form fields for address form.%>
    <%=f.fields_for :address do |a|%>
      <%=a.input :house_number, class: "my-2"%>
      <%=a.input :street_name, class: "my-2"%>
      <%=a.input :suburb, class: "my-2"%>
      <%=a.input :postcode, class: "my-2"%>
      <%=a.input :state, class: "my-2"%>
      <%=a.input :country, class: "my-2"%>
    <%end%>
    <%= f.input :profile_img%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-light text-primary d-block ml-5 my-3" %>
  </div>
<% end %>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<%# <p id="notice"><%= notice %></p> %>

<%# <h1>Profiles</h1> %>

<%# <table> %>
  <%# <thead> %>
    <%# <tr> %>
      <%# <th>User name</th> %>
      <%# <th>First name</th> %>
      <%# <th>Last name</th> %>
      <%# <th>User</th> %>
      <%# <th colspan="3"></th> %>
    <%# </tr> %>
  <%# </thead> %>

  <%# <tbody> %>
    <%# <% @profiles.each do |profile| %> %>
      <%# <tr> %>
        <%# <td><%= profile.user_name %></td> %>
        <%# <td><%= profile.first_name %></td> %>
        <%# <td><%= profile.last_name %></td> %>
        <%# <td><%= profile.user_id %></td> %>
        <%# <td><%= link_to 'Show', profile %></td> %>
        <%# <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <%# <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td> %>
      <%# </tr> %>
    <%# <% end %> %>
  <%# </tbody> %>
<%# </table> %>

<%# <br> %>

<%# <%= link_to 'New Profile', new_profile_path %> %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<%# view for when currently signed in user's profile matches the shown profile's id. edit button only available here.%>
<% if current_user.profile.id == @profile.id %>

<div class="container w-70 mx-auto">
  <%= image_tag @profile.profile_img, class: "w-20" if @profile.profile_img.attached? %>
  <h4>
    <strong><%= @profile.first_name %> <%= @profile.last_name %></strong>
  </h4>

  <p>
    <strong>User name:</strong>
    <%= @profile.user_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @profile.bio %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @profile.address.house_number %> <%= @profile.address.street_name %>, <%= @profile.address.suburb.capitalize %>, <%= @profile.address.state.upcase %>, <%= @profile.address.country.upcase %>
  </p>

  <%= link_to 'Edit Profile', edit_profile_path(@profile), class: "btn btn-light text-primary" %>
</div>
<% else %>
  <%# different view for user if they are not signed in or their profile id does not match the shown profile's id%>
  <h1 class="text-center display-3 my-5"><%= @profile.user_name %>'s Pantry</h1>
  <div class="row justify-content-center">
  <%# user details %>
    <div class="col-sm-5">
      <h2 class="text-center my-3">About me</h2>
      <p class="text-center">
        <%= @profile.address.suburb.capitalize %>,
        <%= @profile.address.state.upcase %>, 
        <%= @profile.address.country %>
      </p>
      <p class="m-3"><%= @profile.bio %></p>
    </div>
    <%# contact form that sends a message to displayed user from user currently signed in%>
    <div class="col-sm-5">
      <h2 class="text-center my-3">Contact</h2>
      <div class="form-group mx-3">
        <%= form_with url: new_message_path do |form| %>
          <%= form.label "message[topic]", "topic" %>
          <%= form.text_field "message[topic]", class: "form-control" %>
          <%= form.label "message[body]", "body" %>
          <%= form.text_area "message[body]", class: "form-control", size: "30x5" %>
          <%= form.hidden_field "message[profile_id]", value: @profile.id %>
          <%= form.submit "Send Message", class: "btn btn-light text-primary d-block mx-auto my-3" %>
        <% end %>
      </div>
    </div>
  </div>
  
  
<%# card deck of all products belonging to selected profile. %>
  <div class="row justify-content-center">
        <% @profile.products.each do |product|%>
            <div class="card col-sm-3 m-2">
                <%= image_tag product.pictures[0], class: "card-image-top" if product.pictures.attached?%>
                <div class="card-body">
                    <h4 class="card-title"><%= product.name %></h4>
                    <p class="card-text"><%= product.description %></p>
                    <%= link_to "View Item", product_path(id: product.id), class: "btn btn-light text-primary mx-auto" %>
                </div>
            </div>
        <% end %>
    </div>
<% end %>
<p id="notice"><%= notice %></p>