config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :profiles
  get 'home/index'
  get 'home/browse', to: 'home#browse', as: 'browse'
  get 'messages/index', to: 'messages#index', as: 'messages'
  get 'messages/show/:id', to: 'messages#show', as: 'message'
  post 'messages/new_message', to: 'messages#new_message', as: 'new_message'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:"home#index"
end

app/views/partials/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-light">
    <%=link_to "Backyard Basket", root_path, class: "navbar-brand mx-3" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <%# only browse shown to user if they are not signed in. %>
            <li class="nav-item active">
                <%=link_to "Browse", browse_path, class: "nav-link"%>
            </li>
            <% if user_signed_in? && current_user.profile %>
            <li class="nav-item active">
                <%=link_to "Your Pantry", products_path, class: "nav-link"%>
            </li>
            <li class="nav-item active">
                <%=link_to "Inbox", messages_path, class: "nav-link"%>
            </li>
            <% end %>
        </ul>
        <ul class="navbar-nav">
            
            <li class="nav-item active">
            <%if user_signed_in? && current_user.profile%>
                <%=link_to "Profile", profile_path(id: profile_id), class: "nav-link"%>
            <%end%>
            </li>
            <%if user_signed_in? && current_user.profile%>
                <li class="nav-item active">
                    <%=link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-light text-danger"%>
                </li>
            <%else%>
                <li class="nav-item active">
                    <%=link_to "Sign in", root_path, class: "nav-link btn btn-light text-primary"%>
                </li>
            <%end%>
        </ul>
    </div>
</div>