config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :profiles
  get 'home/index'
  get 'home/browse', to: 'home#browse', as: 'browse'
  get 'messages/index', to: 'messages#index', as: 'messages'
  get 'messages/show/:id', to: 'messages#show', as: 'message'
  post 'messages/new_message', to: 'messages#new_message', as: 'new_message'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:"home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  # browse link from navbar shows all or just nearby users depending if user is signin or not.
  def browse
    # if user is signed in the should have a geocode address which is queried here and then nearbys searches via API for other addresses within a 5 mile radius. 
    # includes is passed 2 values to preload profiles and profile images. 
    if user_signed_in?
      @nearby_profiles = current_user.profile.address.nearbys(5).includes(:profile, profile: :profile_img_attachment)
    else
    # if user is not signed in return all profiles by default. Placeholder until a search function can be implemented. 
      @profiles = Profile.all.includes(:address, :profile_img_attachment)
    end
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/browse.html.erb
<div class="container">
    <h1 class="text-center mb-5">Find a Grower near you</h1>
    <div class="row justify-content-center">
    <%# two different loops required due to the difference in data being passed from controller depending if user is signed in or not. %>
    <%# view for if user is signed in%>
        <% if user_signed_in? %>
            <% @nearby_profiles.each do |seller|%>
                <div class="card col-sm-3 mx-2">
                    <%= image_tag seller.profile.profile_img, class: "card-image-top" if seller.profile.profile_img.attached?%>
                    <div class="card-body">
                        <h4 class="card-title"><%= seller.profile.user_name %></h4>
                        <p class="card-text text-muted"><%= seller.suburb %></p>
                        <%= link_to "View #{seller.profile.user_name}'s Profile", profile_path(id: seller.profile.id), class: "btn btn-light text-primary mx-auto" %>
                    </div>
                    
                </div>
            <% end %>
    <%# view for if the user is not signed in. shows all profiles instead of just nearby ones. %>     
        <% else %>
            <% @profiles.each do |seller|%>
                <div class="card col-sm-3">
                    <%= image_tag seller.profile_img, class: "card-image-top" if seller.profile_img.attached?%>
                    <div class="card-body">
                        <h4 class="card-title"><%= seller.user_name %></h4>
                        <p class="card-text text-muted"><%= seller.address.suburb %></p>
                        <%= link_to "View #{seller.user_name}'s Profile", profile_path(id: seller.id), class: "btn btn-light text-primary mx-auto" %>
                    </div>
                    
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
<h1 class="text-center display-1 pb-5">Backyard Basket</h1>
    <div class="row justify-content-center">
        <div class="col-sm-5">
            <div class="card">
                <h2 class="card-title mx-auto pt-4 pb-2">Welcome</h2>
                <p class="card-text px-5 pb-1">The Backyard Basket is a place for people to find a better use for the excess veggies, fuits, eggs or other home grown produce that often comes when a crop's season comes around. By linking you into your local community of Home Growers, your pantry or fridge can be stocked with fresh, home grown produce that avoids the detrimental effects of commercial agriculture and transport and allows you to diversify the produce you can get beyond what you backyard may be able to handle growing.</p>
                <p class="card-text px-5 pb-5">Backyard Basket combines the convenience of a modern marketplace, allowing you to view what people are growing or have overflowing from their pantry and easily list your own home grown products, with the age old practice of sharing your backyard bounty with your neighbours and friends</p>
            </div>
        </div>
        <%# hides sign up form on home page if the user is already signed in. %>
        <% if user_signed_in?%>
        <% else %>
            <div class="col-sm-5">
                <div class="card">
                    <h2 class="card-title mx-auto pt-4 pb-2">Sign up</h2>
                    <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                    <%= f.error_notification %>

                    <div class="form-inputs mx-4">
                        <%= f.input :email,
                                    required: true,
                                    autofocus: true,
                                    input_html: { autocomplete: "email" }%>
                        <%= f.input :password,
                                    required: true,
                                    hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                                    input_html: { autocomplete: "new-password" } %>
                        <%= f.input :password_confirmation,
                                    required: true,
                                    input_html: { autocomplete: "new-password" } %>
                    </div>

                    <div class="form-actions mx-4 my-4 text-center">
                        <%= f.button :submit, "Sign up", class: "btn btn-primary"%>
                    </div>
                    <% end %>

                    <%= render "devise/shared/links" %>
                </div>
            </div>
        <% end %>
        
        
        
    </div>
</div>