config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :profiles
  get 'home/index'
  get 'home/browse', to: 'home#browse', as: 'browse'
  get 'messages/index', to: 'messages#index', as: 'messages'
  get 'messages/show/:id', to: 'messages#show', as: 'message'
  post 'messages/new_message', to: 'messages#new_message', as: 'new_message'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:"home#index"
end

app/models/product.rb
class Product < ApplicationRecord
  #one to many relation ship with profile. 
  belongs_to :profile
  # polymorphous relationship with active storage. call pictures on @product to query active record and return array of pictures
  has_many_attached :pictures

  # Validates presence of non optional information critical to products. 
  [:name, :description, :harvested_date, :expiry_date, :stock].each do |v|
    validates v, presence: true
  end
  # prevents excessively long product titles
  validates :name, length: { in: 3..100 }
  # prevents excessively long product details
  validates :description, length: { maximum: 1000 }
  # ensures stock is an integer, is greater than zero and does not exceed 1000 which is an unrealistic amount of stock for home grown produce.
  validates :stock, numericality: { greater_than: 0, less_than_or_equal_to: 1000, only_integer: true } 
  # same validation purpose as stock validations.
  validates :price_per_unit, numericality: { greater_than: 0, less_than_or_equal_to: 1000, only_integer: true}
  # uses https://github.com/adzap/validates_timeliness gem to allow for simplified validation of date-time values. Harvested date cannot be beyond the current date
  validates_date :harvested_date, on_or_before: :today, before_message: "Cannot be later than Today's Date."
  # expiry date must be from tomorrow's date onwards.
  validates_date :expiry_date, after: :today, before_message: "Must be from tomorrow's date onwards"
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    # only shows products belonging to the current signed in user. 
    @products = current_user.profile.products.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    #passes profile id for use in hidden field of form 
    @product.profile_id = current_user.profile.id

    respond_to do |format|
      if @product.save
        # redirects to products index page instead of product show page. 
        format.html { redirect_to products_path, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        # also redirects to products index. 
        format.html { redirect_to products_path, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # pictures has value of empty array to allow for multiple image uploads
    def product_params
      params.require(:product).permit(:name, :description, :organic, :harvested_date, :expiry_date, :stock, :price_per_unit, :profile_id, pictures:[])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :organic %>
    <%= f.input :harvested_date %>
    <%= f.input :expiry_date %>
    <%= f.input :stock %>
    <%= f.input :price_per_unit %>
    <%= f.input :pictures, as: :file, :input_html => { :multiple => true } %>
    <%= f.hidden_field :profile %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="d-block text-center">Your Produce</h1>
<div class="container">
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Organic</th>
      <th>Harvested date</th>
      <th>Expiry date</th>
      <th>Stock</th>
      <th>Price per unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product %></td>
        <td><%= product.description %></td>
        <td><%= product.organic %></td>
        <td><%= product.harvested_date %></td>
        <td><%= product.expiry_date %></td>
        <td><%= product.stock %></td>
        <td><%= product.price_per_unit %></td>
        
      </tr>
      <tr>
        <td><span><%= link_to 'Edit', edit_product_path(product) %></span> <span><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
        
        
        
      </tr>
      
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class: "btn btn-light text-primary" %>
</div>

app/views/products/new.html.erb
<div class="container w-70 mx-auto px-2">
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container p-5 mx-auto">
<p>
  <strong class="d-block">Name:</strong>
  <%= @product.name %>
</p>
<hr>
<p>
  <strong class="d-block">Description:</strong>
  <%= @product.description %>
</p>
<hr>
<p>
  <strong class="d-block">Organic:</strong>
  <%= @product.organic %>
</p>
<hr>
<p>
  <strong class="d-block">Harvested date:</strong>
  <%= @product.harvested_date %>
</p>
<hr>
<p>
  <strong class="d-block">Expiry date:</strong>
  <%= @product.expiry_date %>
</p>
<hr>
<p>
  <strong class="d-block">Stock:</strong>
  <%= @product.stock %>
</p>
<hr>
<p>
  <strong class="d-block">Price per unit:</strong>
  <%= @product.price_per_unit %>
</p>
<hr>
<% if @product.profile.id == current_user.profile.id%>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<% end %>

<%# bootstrap carousel for all pictures attached to product. %>
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% if @product.pictures.attached? %>
      <% @product.pictures.each do |picture|%>
        <div class="carousel-item active">
          <% image_tag picture, class: "d-block w-100"%>
        </div>
      <% end %>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>